#端口
server:
  port: 9300
#  项目名称
spring:
  application:
    name: dynamicDataSource
  #    数据源
  datasource:
    #    数据源2
    cluster:
      - driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/test2?allowMultiQueries=true&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
        key: slave1
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        username: useraa
    #      数据源1
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test1?allowMultiQueries=true&useUnicode=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      username: useraa
